NotFoundError added
axe-api/axe-api pull request #165
Opened 2023-04-15 12:55 UTC by Arifkarakilic

ShowHandler item control status code changed and error class default value bad request made 
Close #132

2023-04-19 18:31 UTC, ozziest requested changes
This is a great start, @Arifkarakilic! 👏 🥳 

I requested some changes. Let's keep coding little bit more. 💪

2023-04-19 18:31 UTC, ozziest commented on src/Handlers/ShowHandler.ts
> +import { StatusCodes } from "http-status-codes";
I remember that I already removed the `http-status-codes` package from dependencies. You can find the `StatusCodes` enum in the `Enum.ts` file. Can you use it?

2023-04-19 22:32 UTC, Arifkarakilic commented
done

2023-04-22 09:30 UTC, ozziest requested changes
Congrats! 👏 👏 It looks great. 
But we need two more things;
- Integration tests: we need to check if really got 404
- Changelog change: we need to increase the version and update changelog file

2023-04-22 09:30 UTC, ozziest commented on src/Handlers/ShowHandler.ts
> +  }//parentı kontrol edip gerçekten varsa 404le item not found döndermemiz gerekiyor
```suggestion
  }
```

2023-05-05 09:57 UTC, ozziest requested changes
We don't need to create a new integration test file. If you execute the following command;

`npm run test:mysql8`

then you can see the following error;

<img width="579" alt="image" src="https://user-images.githubusercontent.com/2325140/236428564-10c43bdb-f58c-40a3-9fc4-bb63514e1bbc.png">

So we should update that test file with the correct HTTP response code.

2023-05-10 19:49 UTC, ozziest requested changes
We need to fix CHANGELOG. ☺️

2023-05-10 20:07 UTC, ozziest approved these changes

2023-05-10 20:07 UTC, merged