Default error handler behaivour changed and logger added
axe-api/axe-api pull request #170
Opened 2023-04-18 21:35 UTC by saracalihan

## Description
If an error other than `ApiError` occurs, it logs it and returns a general error message without any specific data.

Fixed #155 
**Console**: 
![Screenshot_20230419_001921](https://user-images.githubusercontent.com/56413673/232909018-bff634f4-e7a8-4b98-a6b8-66d672cc90d8.png)

**HTTP Response**:
code: `500`
body: 
```json
{
    "error": "An error occurredxx."
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-04-20 19:24 UTC, ozziest requested changes

2023-04-20 19:24 UTC, ozziest commented on src/Builders/RouterBuilder.ts
> +        });
We should move production checks to the `axe-api-template`.

2023-04-22 09:35 UTC, ozziest requested changes
As we talked about in pair programming, we need to provide developers that they can handle errors.

2023-04-22 12:17 UTC, saracalihan commented
> As we talked about in pair programming, we need to provide developers that they can handle errors.

They can handle it with an express error handler in the source code if they don't want to do that axe-api pass error to express's default error handler( that sends HTML file with the error message ).

Today, I will add a basic error handler to template and dev-kit

2023-05-10 20:11 UTC, merged