like query fix
axe-api/axe-api pull request #181
Opened 2023-05-04 13:36 UTC by burakack

## Motivation and Context
Now Devs cant query any non string fields

#96 close

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)

2023-05-04 19:43 UTC, ozziest requested changes
We need integration tests.

PS: 
<img width="574" alt="image" src="https://user-images.githubusercontent.com/2325140/236312718-8ec6aabf-8b7d-4e73-b654-f5bb087651a0.png">

2023-05-04 19:43 UTC, ozziest commented on src/Services/QueryService.ts
> +      where.model.columns.forEach(column=>{
We should check it only for `$like` and `$notLike` operators

2023-05-14 10:52 UTC, ozziest requested changes
@burakack , that's great. 👏 We are so close to merging the PR. Can you add one integration test, please? 

- Try to use LIKE operator on a non-varchar field, and test the error message is correct.

2023-05-14 10:52 UTC, ozziest commented on src/Services/QueryService.ts
> +            `Query field need to be varchar. Unacceptable query field: ${where.field}`
```suggestion
            `You can not use the LIKE/NOT LIKE operator on non-varchar fields: ${where.field}`
```

2023-08-05 17:17 UTC, ozziest commented
@saracalihan is there anything that I can help?

2023-08-23 15:00 UTC, ozziest commented
@burakack do you have any time to keep working on it? 😊

2023-08-24 17:09 UTC, burakack commented
> @burakack do you have any time to keep working on it? 😊

Unfortunately, I can't even find time to drink water. Working life is very tiring. 😞 
I wish I had free time I can't wait to contribute the project

2023-08-24 20:12 UTC, closed without merging