Node version updates
axe-api/axe-api pull request #508
Opened 2024-08-02 04:36 UTC by DavidReque

hi, check the changes

2024-08-03 08:24 UTC, ozziest requested changes
Hey! I just requested one small change. ☺️

2024-08-03 08:24 UTC, ozziest commented on package.json
> +    "rimraf": "^^5.0.5",
```suggestion
    "rimraf": "^5.0.5",
```

2024-08-04 02:39 UTC, DavidReque commented
@ozziest I have made the requested changes.

2024-08-04 13:05 UTC, ozziest approved these changes
Looks great! 👏

2024-08-04 13:09 UTC, ozziest commented
@DavidReque , we have an error on tests;

> npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

You need to execute `npm install` once.

2024-08-05 01:01 UTC, DavidReque commented
hey @ozziest I have run `npm install` to update the file

2024-08-07 17:44 UTC, ozziest commented
Hey @DavidReque !
We are very close to merging this PR. I've noticed some issues on the integration tests and fixed them all. But you need to rebase your PR one more time. ☺️

2024-08-10 17:17 UTC, ozziest commented
Hey @DavidReque . The PR has some conflict. Could you rebase it with `git pull --rebase origin develop`? one more time? ☺️

2024-08-24 15:18 UTC, ozziest commented
Hey @DavidReque, the PR still has some conflicts. Could you rebase it, please? ☺️

2024-08-29 10:41 UTC, closed without merging